name: Test

on:
  push:
    branches: [master, main, develop]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 24
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node24-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node24-
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build Astro

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 24
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node24-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node24-
      - run: npm ci
        name: Install dependencies
      - run: npm run lint
        name: Run linter
